# Generated by Django 3.1.7 on 2021-03-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210307_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text2',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_text2', models.CharField(default=' ', max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.question')),
            ],
        ),
    ]
