# Generated by Django 3.1.7 on 2021-02-26 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('speeches', '0002_auto_20210226_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
